# 数据库连接配置
spring:
  mvc:
    pathmatch:
      #这里配置的这个参数是为了解决spring boot和swagger版本不兼容的问题
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/LoadRunnerX
    username: yxl
    password: yxl
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # Druid连接池配置
    initial-size: 5
    min-idle: 5
    max-active: 20
    filters: stat,wall
    # 配置Druid数据源监控
    datasource:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: yxl
        login-password: yxl
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
            - sheen



#mapper.xml配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8051







